apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: "gateway-{{ .Values.env }}-{{ .Values.appName }}"
  namespace: "{{ .Values.nsName }}"
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: tls-secret