apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim }}-{{ .Values.appName }}
spec:
  storageClassName: {{ .Values.scName }}
  accessModes:
    - {{ .Values.accessModesType }}
  resources:
    requests:
      storage: {{ .Values.requestStorageSize }}
