apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.appName }}
  name: "service-{{ .Values.appName }}"
spec:
  ports:
  - port: {{ .Values.containerPortNumber }}
    protocol: TCP
    targetPort: {{ .Values.containerPortNumber }}
  selector:
    app: {{ .Values.appName }}
status:
  loadBalancer: {}
