apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.GetBase64 (printf "%s/tls.crt" .Values.tlsDir) }}
  tls.key: {{ .Files.GetBase64 (printf "%s/tls.key" .Values.tlsDir) }}
