apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.GetBase64 .Values.tlsDir }}/tls.crt
  tls.key: {{ .Files.GetBase64 .Values.tlsDir }}/tls.key
